from typing import Protocol
from uuid import UUID

from recomendacoes_api.domain.entities import Place


class PlaceRepository(Protocol):
    def list_paginated(self, limit: int, offset: int) -> tuple[int, list[Place]]: ...
    def list_all(self) -> list[Place]: ...
    def find_by_id(self, id: UUID) -> Place | None: ...
    def save(self, place: Place) -> Place: ...
    def update(self, place: Place) -> Place: ...
    def delete(self, id: UUID) -> bool: ...
